import { Button, ComboBox, Slider, Switch, GridBox, CheckBox } from "std-widgets.slint";
import { Theme } from "../ui/theme.slint";



export component Heading inherits Text {
    in-out property <string> heading;
    text: heading;
    font-weight: Theme.text-weight-bold;
    font-size: Theme.heading-text-size;
}

export component Label inherits Text {
    in-out property <string> label;

    text: label;
    font-size: Theme.label-text-size;
}

export component Panel inherits Rectangle {
    in-out property <length> panel-height;
    in-out property <length> panel-width;

    border-width: Theme.window-border-width;
    border-color: Theme.border-colour;
    border-radius: Theme.border-radius;
    background: Theme.panel-box-background;
    height: panel-height;
    width: panel-width;
}

export component Title inherits Text {
    in-out property <string> title;
    text: title;
    color: Theme.title-text-color;
    font-weight: Theme.title-text-weight;
    font-size: Theme.title-text-size;
}

export component Version inherits Text {
    in-out property <string> version;

    text: "v" + version;
    color: Theme.version-text-color;
    font-size: Theme.version-text-size;
    font-weight: Theme.version-text-weight;
}

export component Header inherits Rectangle {
    in-out property <string> version;
    background: Theme.header-background;
    height: Theme.header-height;
    width: Theme.window-width;

    HorizontalLayout {
        alignment: space-between;

        padding: 10px;
        spacing: 20px;
        Title {
            title: Theme.header-title-text;
        }

        Version {
            vertical-alignment: bottom;
            version: version;
        }
    }
}

export component HorizontalSpacer inherits HorizontalLayout {
    in-out property <length> line-width: Theme.horizontal-spacer-width;
    padding: 10px;
    alignment: center;
    Rectangle {
        background: Theme.horizontal-spacer-color;
        width: line-width;
        height: Theme.horizontal-spacer-height;
    }
}

export component VerticalSpacer inherits VerticalLayout {
    in-out property <length> line-height: Theme.vertical-spacer-height;
    padding: 5px;
    alignment: center;
    Rectangle {
        background: Theme.vertical-spacer-color;
        width: Theme.vertical-spacer-width;
        height: line-height;
    }
}

export component StartButton inherits Button {
    in-out property <bool> active;
    callback start_button_pressed(bool);

    states [
        running when active: {
            text: Theme.start-button-running-text;
            primary: true;
        }
        stopped when !active: {
            text: Theme.start-button-stopped-text;
            primary: false;
        }
    ]

    width: Theme.start-button-width;
    height: Theme.start-button-height;
    clicked => {
        active = !active;
        start_button_pressed(active);
    }
}

export component ActionButton inherits Button {
    callback take_action();

    states [
        on when self.pressed: {
            primary: true;
        }
        off when !self.pressed: {
            primary: false;
        }
    ]

    clicked => {
        take_action();
    }
}

export component WaveSelector inherits ComboBox {
    in-out property <string> shape: Theme.wave-shape-default;
    callback wave_shape_selected(string);

    width: Theme.wave-shape-switch-width;
    model: Theme.wave-shape-list;
    current-value: shape;
    selected(shape) => {
        wave_shape_selected(shape);
    }
}

export component DeviceSelector inherits ComboBox {
    in-out property <string> current-device;
    in property <[string]> device-list;
    callback device_selected(string);

    model: device-list;
    selected(device) => {
        device_selected(device);
    }
}

export component MidiSelector inherits ComboBox {
    in property <[string]> list;
    in property <bool> is_enabled: true;
    callback item_selected(int);

    enabled: is_enabled;
    model: list;
    selected() => {
        item_selected(self.current-index);
    }
}

export component AudioDeviceSelector inherits ComboBox {
    in-out property <[string]> list;
    in-out property <bool> is_enabled: true;
    in-out property <string> current-item;
    callback item_selected(string);

    enabled: is_enabled;
    model: list;
    current-value: current-item;

    selected(device) => {
        self.current-value = device;
        item_selected(device);
    }
}

export component LevelSlider inherits Slider {
    in-out property <int> level;
    in-out property <int> minimum-level;
    in-out property <int> maximum-level;
    in-out property <int> level-step;

    callback level_selected(float);

    value: level;
    step: level-step;
    minimum: minimum-level;
    maximum: maximum-level;

    changed value => {
        level = self.value;
        if (self.value < level-step) {
            self.value == 0;
        }
        level_selected(round(self.value));
    }
}

export component OutputLevelSlider inherits Slider {
    in-out property <int> level;
    callback level_selected(int);

    value: level;
    step: Theme.output-level-slider-step;
    minimum: Theme.output-level-slider-minimum;
    maximum: Theme.output-level-slider-maximum;

    changed value => {
        level_selected(round(self.value));
    }
}

export component ADSRSlider inherits Slider {
    in-out property <int> milliseconds;
    callback milliseconds_selected(float);

    value: milliseconds;
    step: Theme.milliseconds-slider-step;
    minimum: Theme.milliseconds-slider-minimum;
    maximum: Theme.milliseconds-slider-maximum;

    changed value => {
        milliseconds = self.value;
        milliseconds_selected(self.value);
    }
}

export component LFOSlider inherits Slider {
    in-out property <float> slider_value;
    callback level_selected(float);

    value: slider_value;

    changed value => {
        slider_value = self.value;
        level_selected(self.value);
    }
}

export component VerticalLabeledIntSlider inherits VerticalLayout {

    in-out property <string> label;
    in-out property <int> slider_value;
    in-out property <string> value_display;
    in-out property <bool> is_bold;
    in-out property <bool> is_enabled: true;
    in-out property <int> step;
    in-out property <int> minimum;
    in-out property <int> maximum;
    in-out property <length> slider_height: Theme.vertical-slider-height;
    in-out property <length> slider_width: Theme.vertical-slider-width;
    in-out property <Orientation> slider_orientation;

    callback new_value_selected(float);

    HorizontalLayout {
        alignment: center;
        Label {
            horizontal-alignment: center;
            font-weight: is_bold ? Theme.text-weight-bold : Theme.text-weight-regular;
            label: label;
        }

        Label {
            font-weight: is_bold ? Theme.text-weight-bold : Theme.text-weight-regular;
            label: value_display;
        }
    }

    Slider {
        height: slider_height;
        width: slider_width;
        orientation: slider_orientation;
        enabled: is_enabled;
        value: slider_value;
        step: step;
        minimum: minimum;
        maximum: maximum;

        changed value => {
            slider_value = self.value;
            if (self.value < self.step) {
                self.value == 0;
            }
            new_value_selected(self.value);
        }
    }
}

export component VerticalLabeledFloatSlider inherits VerticalLayout {

    in-out property <string> label;
    in-out property <float> slider_value;
    in-out property <string> value_display;
    in-out property <bool> is_bold;
    in-out property <bool> is_enabled: true;
    in-out property <float> step;
    in-out property <float> minimum;
    in-out property <float> maximum;
    in-out property <length> slider_height: Theme.vertical-slider-height;
    in-out property <length> slider_width: Theme.vertical-slider-width;
    in-out property <Orientation> slider_orientation;

    callback new_value_selected(float);

    HorizontalLayout {
        alignment: center;
        Label {
            horizontal-alignment: center;
            font-weight: is_bold ? Theme.text-weight-bold : Theme.text-weight-regular;
            label: label;
        }

        Label {
            font-weight: is_bold ? Theme.text-weight-bold : Theme.text-weight-regular;
            label: value_display;
        }
    }

    Slider {
        width: slider_width;
        height: slider_height;
        orientation: slider_orientation;
        enabled: is_enabled;
        value: slider_value;
        step: step;
        minimum: minimum;
        maximum: maximum;

        changed value => {
            slider_value = self.value;
            if (self.value < step) {
                self.value == 0;
            }
            new_value_selected(self.value);
        }
    }
}

export component ActivationSwitch inherits Switch {
    callback activation_toggled(bool);
    in-out property <bool> activated: self.checked;
    in-out property <string> activated-text;
    in-out property <string> not-activated-text;

    text: self.checked ? activated-text : not-activated-text;
    width: Theme.activation-switch-width;

    toggled() => {
        activation_toggled(self.checked)
    }
}

export component FilterSlider inherits Slider {
    in-out property <int> number_of_poles: Theme.filter-poles-slider-default;
    callback number_of_poles_selected(int);

    width: Theme.filter-poles-slider-width;
    value: number_of_poles;
    step: Theme.filter-poles-slider-step;
    minimum: Theme.filter-poles-slider-minimum;
    maximum: Theme.filter-poles-slider-maximum;

    released(value) => {
        self.value = round(value);
        number_of_poles = round(value);
        number_of_poles_selected(round(value));
    }
}

export component ArpNoteBox inherits HorizontalLayout {

    in-out property <bool> check-default-note;
    callback note_active(bool);

    alignment: center;

    box := CheckBox {
        checked: check-default-note;
        toggled() => {
            check-default-note = self.checked;
            note_active(self.checked)
        }
    }
}

export component ArpTableRow inherits HorizontalLayout {

    in-out property <string> octave-number;
    in-out property <int> row-number;
    in-out property <bool> is-default-note;
    property <int> box-offset: (12 * row-number);

    callback note_activated(int);
    callback note_deactivated(int);

    spacing: 20px;
    alignment: space-between;

    Label {
        width: 60px;
        label: octave-number;
    }

    box0 := ArpNoteBox {
        check-default-note: is-default-note;
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset);
            } else {
                note_deactivated(box-offset);
            }
        }
    }

    box1 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 1);
            } else {
                note_deactivated(box-offset + 1);
            }
        }
    }

    box2 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 2);
            } else {
                note_deactivated(box-offset + 2);
            }
        }
    }

    box3 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 3);
            } else {
                note_deactivated(box-offset + 3);
            }
        }
    }

    box4 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 4);
            } else {
                note_deactivated(box-offset + 4);
            }
        }
    }

    box5 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 5);
            } else {
                note_deactivated(box-offset + 5);
            }
        }
    }

    box6 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 6);
            } else {
                note_deactivated(box-offset + 6);
            }
        }
    }

    box7 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 7);
            } else {
                note_deactivated(box-offset + 7);
            }
        }
    }

    box8 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 8);
            } else {
                note_deactivated(box-offset + 8);
            }
        }
    }

    box9 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 9);
            } else {
                note_deactivated(box-offset + 9);
            }
        }
    }

    box10 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 10);
            } else {
                note_deactivated(box-offset + 10);
            }
        }
    }

    box11 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 11);
            } else {
                note_deactivated(box-offset + 11);
            }
        }
    }
}

export component ArpTableLastRow inherits HorizontalLayout {

    in-out property <string> octave-number;
    in-out property <int> row-number;
    property <int> box-offset: (12 * row-number);

    callback note_activated(int);
    callback note_deactivated(int);

    spacing: 20px;
    alignment: space-between;

    Label {
        width: 60px;
        label: octave-number;
    }

    box1 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset);
            } else {
                note_deactivated(box-offset);
            }
        }
    }

    box2 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 1);
            } else {
                note_deactivated(box-offset + 1);
            }
        }
    }

    box3 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 2);
            } else {
                note_deactivated(box-offset + 2);
            }
        }
    }

    box4 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 3);
            } else {
                note_deactivated(box-offset + 3);
            }
        }
    }

    box5 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 4);
            } else {
                note_deactivated(box-offset + 4);
            }
        }
    }

    box6 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 5);
            } else {
                note_deactivated(box-offset + 5);
            }
        }
    }

    box7 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 6);
            } else {
                note_deactivated(box-offset + 6);
            }
        }
    }

    box8 := ArpNoteBox {
        note_active(is_checked) => {
            if (is_checked) {
                note_activated(box-offset + 7);
            } else {
                note_deactivated(box-offset + 7);
            }
        }
    }

    Label {
        label: " - ";
    }

    Label {
        label: " - ";
    }

    Label {
        label: " - ";
    }

    Label {
        label: " - ";
    }
}

export component ArpTableFirstRow inherits HorizontalLayout {

    spacing: 20px;
    alignment: space-between;

    Label {
        width: 60px;
        label: "Octave";
    }

    Label {
        label: "C";
    }

    Label {
        label: "C#/Db";
    }

    Label {
        label: "D";
    }

    Label {
        label: "D#/Eb";
    }

    Label {
        label: "E";
    }

    Label {
        label: "F";
    }

    Label {
        label: "F#/Gb";
    }

    Label {
        label: "G";
    }

    Label {
        label: "G#/Ab";
    }

    Label {
        label: "A";
    }

    Label {
        label: "A#/Bb";
    }

    Label {
        label: "B";
    }
}

export component OscilatorControls inherits HorizontalLayout {

    in-out property <bool> is_sub: false;
    in-out property <int> oscillator_number;
    in-out property <string> heading;

    callback wave_shape_selected(string, int);
    callback wave_level_selected(float, int);
    callback wave_shaper_amount_changed(float, int);
    callback wave_mod_amount_changed(float, int);
    callback wave_mod_speed_changed(float, int);
    callback wave_tuning_changed(int, int);
    callback wave_specific_parameters_selected(float, float, int);

    alignment: space-between;
    spacing: 10px;
    padding: 10px;

    VerticalLayout {
        spacing: 10px;

        VerticalLayout {

            Heading {
                horizontal-alignment: center;
                heading: heading;
            }

            HorizontalSpacer { }

            osc_selector := WaveSelector {
                height: Theme.wave-selector-height;
                width: Theme.wave-selector-width;

                wave_shape_selected(shape) => {
                    if (shape == Theme.osc-fm-amount-wave-shape) {
                        osc_fm_amount.is_enabled = true;
                        osc_fm_ratio.is_enabled = true;
                        osc_am_amount.is_enabled = false;
                        osc_pulse_width.is_enabled = false;
                    } else if (shape == Theme.osc-am-amount-wave-shape) {
                        osc_fm_amount.is_enabled = false;
                        osc_fm_ratio.is_enabled = false;
                        osc_am_amount.is_enabled = true;
                        osc_pulse_width.is_enabled = false;
                    } else if (shape == Theme.osc-pulse-width-wave-shape) {
                        osc_fm_amount.is_enabled = false;
                        osc_fm_ratio.is_enabled = false;
                        osc_am_amount.is_enabled = false;
                        osc_pulse_width.is_enabled = true;
                    } else {
                        osc_fm_amount.is_enabled = false;
                        osc_fm_ratio.is_enabled = false;
                        osc_am_amount.is_enabled = false;
                        osc_pulse_width.is_enabled = false;
                    }

                    wave_shape_selected(shape, oscillator_number);
                }
            }
        }

        osc_level := VerticalLabeledIntSlider {
            label: Theme.oscillator-level-text;
            slider_value: is_sub ? Theme.sub-level-slider-default : Theme.osc-level-slider-default;
            step: Theme.osc-level-slider-step;
            minimum: Theme.osc-level-slider-minimum;
            maximum: Theme.osc-level-slider-maximum;

            new_value_selected(level) => {
                wave_level_selected(level / 100, oscillator_number);
            }
        }
    }

    VerticalSpacer {
        line-height: 100px;
    }

    VerticalLayout {

        osc_tuning := VerticalLabeledIntSlider {
            label: Theme.oscillator-tuning-text;
            value_display: Theme.osc-tuning-slider-unison;
            slider_value: Theme.osc-tuning-slider-default;
            step: Theme.osc-tuning-slider-step;
            minimum: Theme.osc-tuning-slider-minimum;
            maximum: Theme.osc-tuning-slider-maximum;

            new_value_selected(interval) => {
                if (interval == 0) {
                    self.value_display = Theme.osc-tuning-slider-unison;
                } else if (interval > 0) {
                    self.value_display = "+" + round(interval) + Theme.oscillator-tuning-value-suffix;
                } else {
                    self.value_display = round(interval) + Theme.oscillator-tuning-value-suffix;
                }
                wave_tuning_changed(interval, oscillator_number);
            }
        }

        osc_shape := VerticalLabeledFloatSlider {
            label: Theme.oscillator-shape-text;
            slider_value: Theme.wave_shaper-amount-slider-default;
            step: Theme.wave_shaper-amount-slider-step;
            minimum: Theme.wave_shaper-amount-slider-minimum;
            maximum: Theme.wave_shaper-amount-slider-maximum;

            new_value_selected(amount) => {
                wave_shaper_amount_changed(round(amount * 10.0) / 10.0, oscillator_number);
            }
        }
    }

    VerticalSpacer {
        line-height: 100px;
    }

    VerticalLayout {
        spacing: 10px;

        VerticalLayout {
            spacing: 10px;

            osc_mod_amount := VerticalLabeledFloatSlider {
                label: Theme.oscillator-mod-amount-text;
                value_display: (round(self.slider_value * 100)) + Theme.oscillator-mod-amount-suffix;
                slider_value: Theme.osc-mod-amount-slider-default;
                step: Theme.osc-mod-amount-slider-step;
                minimum: Theme.osc-mod-amount-slider-minimum;
                maximum: Theme.osc-mod-amount-slider-maximum;

                new_value_selected(amount) => {
                    wave_mod_amount_changed(amount, oscillator_number);
                }
            }

            osc_mod_speed := VerticalLabeledFloatSlider {
                label: Theme.oscillator-mod-speed-text;
                value_display: (round(self.slider_value * 100) / 100) + Theme.oscillator-mod-speed-suffix;
                slider_value: Theme.osc-mod-speed-slider-default;
                step: Theme.osc-mod-speed-slider-step;
                minimum: Theme.osc-mod-speed-slider-minimum;
                maximum: Theme.osc-mod-speed-slider-maximum;

                new_value_selected(speed_hz) => {
                    wave_mod_speed_changed(speed_hz, oscillator_number);
                }
            }
        }
    }

    VerticalSpacer {
        line-height: 100px;
    }

    VerticalLayout {
        spacing: 10px;

        osc_fm_amount := VerticalLabeledIntSlider {
            is_enabled: false;
            label: Theme.oscillator-fm-amount-text;
            slider_value: Theme.osc-fm-amount-slider-default;
            step: Theme.osc-fm-amount-slider-step;
            minimum: Theme.osc-fm-amount-slider-minimum;
            maximum: Theme.osc-fm-amount-slider-maximum;

            new_value_selected(amount) => {
                wave_specific_parameters_selected(amount * Theme.osc-fm-amount-slider-adjustment-factor, osc_fm_ratio.slider_value / 2,
                    oscillator_number);
            }
        }

        osc_fm_ratio := VerticalLabeledIntSlider {
            is_enabled: false;
            label: Theme.oscillator-fm-ratio-text;
            value_display: osc_fm_ratio.slider_value / 2 + Theme.oscillator-fm-ratio-suffix;
            slider_value: Theme.osc-fm-ratio-slider-default;
            step: Theme.osc-fm-ratio-slider-step;
            minimum: Theme.osc-fm-ratio-slider-minimum;
            maximum: Theme.osc-fm-ratio-slider-maximum;

            new_value_selected(ratio) => {
                wave_specific_parameters_selected(osc_fm_amount.slider_value * Theme.osc-fm-amount-slider-adjustment-factor, ratio / 2, oscillator_number);
            }
        }
    }

    VerticalSpacer {
        line-height: 100px;
    }

    VerticalLayout {
        spacing: 10px;

        osc_am_amount := VerticalLabeledIntSlider {
            is_enabled: false;
            label: Theme.oscillator-am-amount-text;
            slider_value: Theme.osc-am-amount-slider-default;
            step: Theme.osc-am-amount-slider-step;
            minimum: Theme.osc-am-amount-slider-minimum;
            maximum: Theme.osc-am-amount-slider-maximum;

            new_value_selected(amount) => {
                wave_specific_parameters_selected(amount / 2, 0, oscillator_number);
            }
        }

        osc_pulse_width := VerticalLabeledFloatSlider {
            is_enabled: false;
            label: Theme.oscillator-pulse-width-text;
            slider_value: Theme.osc-pulse-width-slider-default;
            step: Theme.osc-pulse-width-slider-step;
            minimum: Theme.osc-pulse-width-slider-minimum;
            maximum: Theme.osc-pulse-width-slider-maximum;

            new_value_selected(width) => {
                wave_specific_parameters_selected(width, 0, oscillator_number);
            }
        }
    }
}
