import { Button, ComboBox, Slider, Switch } from "std-widgets.slint";
import { Theme } from "../ui/theme.slint";

export component Heading inherits Text {
    in-out property <string> heading;

    text: heading;
    font-weight: Theme.text-weight-bold;
    font-size: Theme.heading-text-size;
}

export component Label inherits Text {
    in-out property <string> label;

    text: label;
    font-size: Theme.label-text-size;
}

export component StartButton inherits Button {
    in-out property <bool> active;
    callback tone_start_button_pressed(bool);

    states [
        running when active: {
            text: Theme.start-button-running-text;
            primary: true;
        }
        stopped when !active: {
            text: Theme.start-button-stopped-text;
            primary: false;
        }
    ]

    width: Theme.start-button-width;
    height: Theme.start-button-height;
    clicked => {
        active = !active;
        tone_start_button_pressed(active);
    }
}

export component ActionButton inherits Button {
    callback take_action();

    states [
        on when self.pressed: {
            primary: true;
        }
        off when !self.pressed: {
            primary: false;
        }
    ]

    clicked => {
        take_action();
    }
}

export component WaveSelector inherits ComboBox {
    in-out property <string> shape: Theme.wave-shape-default;
    callback wave_shape_selected(string);

    width: Theme.wave-shape-switch-width;
    model: Theme.wave-shape-list;
    current-value: shape;
    selected(shape) => {
        wave_shape_selected(shape);
    }
}

export component LevelSlider inherits Slider {
    in-out property <int> level;
    in-out property <int> minimum-level;
    in-out property <int> maximum-level;
    in-out property <int> level-step;

    callback level_selected(float);

    value: level;
    step: level-step;
    minimum: minimum-level;
    maximum: maximum-level;

    changed value => {
        level = self.value;
        if (self.value < level-step) {
            self.value == 0;
        }
        level_selected(round(self.value));
    }
}

export component OutputLevelSlider inherits Slider {
    in-out property <int> level;
    callback level_selected(int);

    value: level;
    step: Theme.output-level-slider-step;
    minimum: Theme.output-level-slider-minimum;
    maximum: Theme.output-level-slider-maximum;

    changed value => {
        level_selected(round(self.value));
    }
}

export component ADSRSlider inherits Slider {
    in-out property <int> milliseconds;
    callback milliseconds_selected(float);

    value: milliseconds;
    step: Theme.milliseconds-slider-step;
    minimum: Theme.milliseconds-slider-minimum;
    maximum: Theme.milliseconds-slider-maximum;

    changed value => {
        milliseconds = self.value;
        milliseconds_selected(self.value);
    }
}

export component LFOSlider inherits Slider {
    in-out property <float> slider_value;
    callback level_selected(float);

    value: slider_value;

    changed value => {
        slider_value = self.value;
        level_selected(self.value);
    }
}

export component ActivationSwitch inherits Switch {
    callback activation_toggled(bool);
    in-out property <bool> activated: self.checked;
    in-out property <string> activated-text;
    in-out property <string> not-activated-text;

    text: self.checked ? activated-text : not-activated-text;
    width: Theme.activation-switch-width;

    toggled() => {
        activation_toggled(self.checked)
    }
}

export component FilterSlider inherits Slider {
    in-out property <int> number_of_poles: Theme.filter-poles-slider-default;
    callback number_of_poles_selected(int);

    width: Theme.filter-poles-slider-width;
    value: number_of_poles;
    step: Theme.filter-poles-slider-step;
    minimum: Theme.filter-poles-slider-minimum;
    maximum: Theme.filter-poles-slider-maximum;

    released(value) => {
        self.value = round(value);
        number_of_poles = round(value);
        number_of_poles_selected(round(value));
    }
}
