import { Heading, Label, LFOSlider, LevelSlider, ActivationSwitch } from "../ui/components.slint";
import { Theme } from "../ui/theme.slint";

export component DynamicsPanel inherits HorizontalLayout {

    callback compressor_activated(bool);
    callback compressor_threshold_changed(float);
    callback compressor_ratio_changed(float);
    callback limiter_activated(bool);
    callback limiter_threshold_changed(float);
    callback clipper_activated(bool);
    callback clipper_threshold_changed(float);

    Rectangle {
        border-width: Theme.window-border-width;
        border-color: Theme.border-colour;
        border-radius: Theme.border-radius;
        background: Theme.adrs-box-background;

        VerticalLayout {
            alignment: start;
            spacing: 20px;
            padding: 10px;

            HorizontalLayout {
                alignment: start;
                spacing: 20px;

                VerticalLayout {
                    spacing: 10px;

                    Heading {
                        horizontal-alignment: center;
                        heading: Theme.compressor-heading-text;
                    }

                    ActivationSwitch {
                        activated-text: Theme.activation-switch-active-text;
                        not-activated-text: Theme.activation-switch-not-active-text;

                        activation_toggled => {
                            compressor_threshold.enabled = self.activated;
                            compressor_ratio.enabled = self.activated;
                            compressor_activated(self.checked);
                        }
                    }

                    Label {
                        label: Theme.compressor-threshold-text + round(compressor_threshold.slider_value);
                    }

                    compressor_threshold := LFOSlider {
                        slider_value: Theme.compressor-threshold-default;
                        step: Theme.compressor-threshold-step;
                        minimum: Theme.compressor-threshold-minimum;
                        maximum: Theme.compressor-threshold-maximum;
                        enabled: false;
                        level_selected(level) => {
                            compressor_threshold_changed(round(level));
                        }
                    }

                    Label {
                        label: Theme.compressor-ratio-text + round(compressor_ratio.value) + Theme.compressor-ratio-suffix;
                    }

                    compressor_ratio := LevelSlider {
                        value: Theme.compressor-ratio-default;
                        step: Theme.compressor-ratio-step;
                        minimum: Theme.compressor-ratio-minimum;
                        maximum: Theme.compressor-ratio-maximum;
                        enabled: false;
                        level_selected(level) => {
                            compressor_ratio_changed(1 / round(level));
                        }
                    }
                }
            }
        }
    }

    Rectangle {
        border-width: Theme.window-border-width;
        border-color: Theme.border-colour;
        border-radius: Theme.border-radius;
        background: Theme.adrs-box-background;
        VerticalLayout {
            alignment: start;
            spacing: 20px;
            padding: 10px;
            HorizontalLayout {
                alignment: start;
                spacing: 20px;
                VerticalLayout {
                    spacing: 10px;
                    Heading {
                        horizontal-alignment: center;
                        heading: Theme.limiter-heading-text;
                    }

                    ActivationSwitch {
                        activated-text: Theme.activation-switch-active-text;
                        not-activated-text: Theme.activation-switch-not-active-text;
                        activation_toggled => {
                            limiter_threshold.enabled = self.activated;
                            limiter_activated(self.checked);
                        }
                    }

                    Label {
                        label: Theme.limiter-threshold-text + round(limiter_threshold.slider_value);
                    }

                    limiter_threshold := LFOSlider {
                        slider_value: Theme.limiter-threshold-default;
                        step: Theme.limiter-threshold-step;
                        minimum: Theme.limiter-threshold-minimum;
                        maximum: Theme.limiter-threshold-maximum;
                        enabled: false;
                        level_selected(level) => {
                            limiter_threshold_changed(round(level));
                        }
                    }
                }
            }
        }
    }

    Rectangle {
        border-width: Theme.window-border-width;
        border-color: Theme.border-colour;
        border-radius: Theme.border-radius;
        background: Theme.adrs-box-background;
        VerticalLayout {
            alignment: start;
            spacing: 20px;
            padding: 10px;
            HorizontalLayout {
                alignment: start;
                spacing: 20px;
                VerticalLayout {
                    spacing: 10px;
                    Heading {
                        horizontal-alignment: center;
                        heading: Theme.clipper-heading-text;
                    }

                    ActivationSwitch {
                        activated-text: Theme.activation-switch-active-text;
                        not-activated-text: Theme.activation-switch-not-active-text;
                        activation_toggled => {
                            clipper_threshold.enabled = self.activated;
                            clipper_activated(self.checked);
                        }
                    }

                    Label {
                        label: Theme.clipper-threshold-text + round(clipper_threshold.slider_value);
                    }

                    clipper_threshold := LFOSlider {
                        slider_value: Theme.clipper-threshold-default;
                        step: Theme.clipper-threshold-step;
                        minimum: Theme.clipper-threshold-minimum;
                        maximum: Theme.clipper-threshold-maximum;
                        enabled: false;
                        level_selected(level) => {
                            clipper_threshold_changed(round(level));
                        }
                    }
                }
            }
        }
    }
}
