import { Heading, Label, FilterSlider, LevelSlider  } from "../ui/components.slint";
import { Theme } from "../ui/theme.slint";

export component FilterPanel inherits VerticalLayout {
    alignment: start;

    callback number_of_poles_selected(int);
    callback filter_cutoff_value_changed(float);
    callback filter_resonance_value_changed(float);

    Rectangle {
        border-width: Theme.window-border-width;
        border-color: Theme.border-colour;
        border-radius: Theme.border-radius;
        background: Theme.panel-box-background;

        VerticalLayout {
            alignment: start;
            spacing: 10px;
            padding: 20px;

            Heading {
                heading: Theme.filter-header-text;
            }

            HorizontalLayout {
                alignment: start;
                spacing: 10px;
                padding: 20px;

                VerticalLayout {
                    spacing: 10px;

                    Label {
                        label: Theme.filter-poles-label-text;
                    }

                    Label {
                        label: Theme.filter-cutoff-text;
                    }

                    Label {
                        label: Theme.filter-resonance-text;
                    }
                }

                VerticalLayout {
                    spacing: 10px;

                    Label {
                        horizontal-alignment: center;
                        label: filter_poles.number_of_poles;
                    }

                    Label {
                        horizontal-alignment: center;
                        width: Theme.filter-cutoff-value-width;
                        label: round(filter_cutoff.level);
                    }

                    Label {
                        horizontal-alignment: center;
                        label: 100 - filter_resonance.level;
                    }
                }

                VerticalLayout {
                    spacing: 10px;

                    filter_poles := FilterSlider {
                        number_of_poles_selected(number_of_poles) => {
                            root.number_of_poles_selected(number_of_poles);
                        }
                    }

                    filter_cutoff := LevelSlider {
                        width: 200px;
                        orientation: horizontal;

                        level: Theme.filter-cutoff-slider-default;
                        level-step: self.level * Theme.filter-cutoff-slider-step-factor;
                        minimum-level: Theme.filter-cutoff-slider-minimum;
                        maximum-level: Theme.filter-cutoff-slider-maximum;
                        level_selected(level) => {
                            filter_cutoff_value_changed(level);
                        }
                    }

                    filter_resonance := LevelSlider {
                        width: 200px;
                        orientation: horizontal;

                        level: Theme.filter-resonance-slider-default;
                        level-step: Theme.filter-resonance-slider-step;
                        minimum-level: Theme.filter-resonance-slider-minimum;
                        maximum-level: Theme.filter-resonance-slider-maximum;
                        level_selected(level) => {
                            filter_resonance_value_changed((100 - level) / 100);
                        }
                    }
                }
            }
        }
    }
}
