import { Panel, Heading, Label, MidiSelector } from "../ui/components.slint";
import { Theme } from "../ui/theme.slint";

export component SettingsPanel inherits HorizontalLayout {

    in-out property <[string]> midi_input_ports;
    callback midi_port_selected(int);

    Panel {
        width: 100%;

        HorizontalLayout {
            alignment: start;

            VerticalLayout {
                alignment: start;
                padding: 10px;
                spacing: 10px;

                Heading {
                    heading: "Midi Settings";
                }

                Label {
                    label: "Midi Device";
                }

                MidiSelector {
                    port-list: midi_input_ports;
                    port_selected(port_index) => {
                        root.midi_port_selected(port_index);
                    }
                }


                Label {
                    label: "Midi Channel";
                }

                MidiSelector {
                    port-list: ["Omni","1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16"];
                }


            }
        }

    }
}