import { Panel, Heading, Label, MidiSelector, AudioDeviceSelector } from "../ui/components.slint";
import { Theme } from "../ui/theme.slint";

export component SettingsPanel inherits HorizontalLayout {
    padding: 5px;
    in-out property <[string]> midi_input_ports;
    in-out property <[string]> audio_output_device_list;
    in-out property <[string]> audio_output_channels;
    in-out property <string> audio_output_left_channel;
    in-out property <string> audio_output_right_channel;
    in-out property <string> audio_output_device;

    callback midi_port_selected(int);
    callback midi_channel_selected(int);
    callback audio_device_selected(string);
    callback audio_channels_selected(string, string);

    Panel {
        panel-height: Theme.settings-panel-height;
        panel-width: Theme.settings-panel-width;

        HorizontalLayout {
            alignment: start;

            VerticalLayout {
                alignment: start;
                padding: 10px;
                spacing: 10px;

                Heading {
                    heading: Theme.settings-midi-text;
                }

                Label {
                    label: Theme.settings-midi-port-text;
                }

                MidiSelector {
                    list: midi_input_ports;
                    item_selected(port_index) => {
                        root.midi_port_selected(port_index);
                    }
                }

                Label {
                    label: Theme.settings-midi-channel-text;
                }

                MidiSelector {
                    list: Theme.midi_channel_list;
                    item_selected(channel) => {
                        root.midi_channel_selected(channel);
                    }
                }
            }
        }
    }

    Panel {
        panel-height: Theme.settings-panel-height;
        panel-width: Theme.settings-panel-width;

        HorizontalLayout {
            alignment: start;

            VerticalLayout {
                alignment: start;
                padding: 10px;
                spacing: 10px;

                Heading {
                    heading: Theme.settings-audio-text;
                }

                Label {
                    label: Theme.settings-audio-output-device-text;
                }

                AudioDeviceSelector {
                    list: audio_output_device_list;
                    item_selected(device) => {
                        root.audio_device_selected(device);
                    }
                }

                Label {
                    label: Theme.settings-audio-channels-text;
                }

                HorizontalLayout {
                    spacing: 10px;

                    left_channel := AudioDeviceSelector {
                        list: audio_output_channels;
                        current-value: audio_output_left_channel;
                        item_selected(channel) => {
                            root.audio_channels_selected(channel, right_channel.current-value);
                        }
                    }

                    right_channel := AudioDeviceSelector {
                        states [
                            Mono when audio_output_right_channel != "": {
                                right_channel.is_enabled: true;
                            }
                            MultiChannel when audio_output_right_channel == "": {
                                right_channel.is_enabled: false;
                            }
                        ]

                        list: audio_output_channels;
                        current-value: audio_output_right_channel;
                        item_selected(channel) => {
                            root.audio_channels_selected(left_channel.current_value, channel);
                        }
                    }
                }
            }
        }
    }
}
