
export global Theme {

    // Main Window
    out property <string> window-title: "Oscillator Playground";
    out property <length> window-width: 1000px;
    out property <length> window-height: 750px;
    out property <length> window-border-width: 2px;
    out property <color> window-background: #101010;
    out property <color> border-colour: #404040;
    out property <length> border-width: 2px;
    out property <length> border-radius: 15px;
    out property <color> header-background: #252525;
    out property <length> top-panel-row-height: 550px;
    out property <string> tab-synth-title: "Synth Engine";
    out property <string> tab-effects-title: "Effects";
    out property <string> tab-arpeggiator-title: "Arpeggiator";
    out property <color> panel-box-background:#202020;

    // Panel Sized
    out property <length> envelope-panel-width: 330px;
    out property <length> lfo-panel-width: 173px;
    out property <length> oscillator-panel-width: 670px;

    // Fonts
    out property <color> text-color: #AAAAAA;
    out property <color> greyed-out: #444444;
    out property <int> text-weight-bold: 800;
    out property <length> text-size: 14px;
    out property <length> label-text-size: 14px;
    out property <length> heading-text-size: 16px;


    // Arpeggiator
    out property <string> arpeggiator-heading-text: "Note Selection";
    out property <string> arpeggiator-button-text: "Update Notes";
    out property <length> arpeggiator-button-width: 150px;
    out property <length> arpeggiator-button-height: 35px;
    out property <string> arpeggiator-note-order-text: "Note Order: ";
    out property <string> arpeggiator-switch-active-text: "Random";
    out property <string> arpeggiator-switch-not-active-text: "Order Selected";
    out property <length> arpeggiator-switch-width: 200px;


    //
    // Components
    //

    // Slider Adjustment Ratios
    out property <float> lfo-slider-step-ratio: 0.01;



    // Start Button
    out property <string> start-button-running-text: "Stop";
    out property <string> start-button-stopped-text: "Start";
    out property <length> start-button-width: 150px;
    out property <length> start-button-height: 35px;

    // Resync Buttons
    out property <string> resync-button-text: "Resync Oscillators";
    out property <string> resync-lfo-button-text: "Resync Modulation";
    out property <length> resync-button-width: 150px;
    out property <length> resync-button-height: 35px;

    // Detune Switch
    out property <length> mode-switch-width: 250px;
    out property <length> mode-switch-height: 30px;
    out property <length> mode-switch-spacer: 15px;

    // Output Level
    out property <int> output-level-minimum: -30;
    out property <int> output-level-maximum: 0;
    out property <int> output-level-step-size: 1;

    // Wave Selector
    out property <length> wave-shape-switch-width: 150px;
    out property <[string]> wave-shape-list: ["Sine", "Ramp", "Saw", "Square", "SuperSaw", "Triangle", "Noise"];
    out property <string> wave-shape-default: "Sine";

    // Oscillator Level Slider
    out property <int> osc-level-slider-step: 1;
    out property <int> osc-level-slider-minimum: 0;
    out property <int> osc-level-slider-maximum: 100;
    out property <int> osc-level-slider-default: 100;
    out property <int> sub-level-slider-default: 0;
    out property <int> detune-amount-slider-default: 0;

    // Oscillator Tuning Slider
    out property <int> osc-tuning-slider-step: 1;
    out property <int> osc-tuning-slider-minimum: -12;
    out property <int> osc-tuning-slider-maximum: 12;
    out property <int> osc-tuning-slider-default: 0;
    out property <string> osc-tuning-slider-unison: "Unison";



    // Oscillator Modulation Slider
    out property <float> osc-mod-fine-speed-slider-step: 0.01;
    out property <float> osc-mod-fine-speed-slider-minimum: 0.0;
    out property <float> osc-mod-fine-speed-slider-default: 0.01;
    out property <float> osc-mod-fine-speed-slider-maximum: 10.0;
    out property <float> osc-mod-amount-slider-step: 0.01;
    out property <float> osc-mod-amount-slider-minimum: 0.0;
    out property <float> osc-mod-amount-slider-maximum: 1.0;
    out property <float> osc-mod-amount-slider-default: 0.0;

    // Filter Cutoff Slider
    out property <int> filter-cutoff-slider-step-factor: 0.05;
    out property <int> filter-cutoff-slider-minimum: 0;
    out property <int> filter-cutoff-slider-maximum: 18500;
    out property <int> filter-cutoff-slider-default: 18500;
    out property <length> filter-cutoff-value-width: 75px;
    out property <int> filter-cutoff-display-adjustment-factor: 185;

    // Filter Resonance Slider
    out property <int> filter-resonance-slider-step: 1;
    out property <int> filter-resonance-slider-minimum: 40;
    out property <int> filter-resonance-slider-maximum: 100;
    out property <float> filter-resonance-slider-default: 100;

    // Filter Poles Slider
    out property <int> filter-poles-slider-step: 1;
    out property <int> filter-poles-slider-minimum: 1;
    out property <int> filter-poles-slider-maximum: 4;
    out property <int> filter-poles-slider-default: 2;
    out property <length> filter-poles-slider-width: 100px;

    // Output Level Slider
    out property <int> output-level-slider-step: 1;
    out property <int> output-level-slider-minimum: 40;
    out property <int> output-level-slider-maximum: 100;
    out property <int> output-level-slider-default: 90;
    out property <length> output-level-slider-width: 150px;
    out property <length> output-level-slider-text-width: 75px;


    // Output Level Balanced Switch
    out property <string> output-level-constant-active-text: "Constant Level";
    out property <string> output-level-constant-not-active-text: "Valiable Level";


    // ADSR Slider 
    out property <int> milliseconds-slider-step: 10;
    out property <int> milliseconds-slider-minimum: 10;
    out property <int> milliseconds-slider-maximum: 2000;

    // Sustain Level Slider
    out property <int> envelope-sustain-level-step: 1;
    out property <int> envelope-sustain-level-minimum: 0;
    out property <int> envelope-sustain-level-maximum: 40;

    // Activation Switch
    out property <string> activation-switch-active-text: "Active";
    out property <string> activation-switch-not-active-text: "Not Active";
    out property <length> activation-switch-width: 125px;

    // Envelope ADRS Defaults
    out property <int> envelope-attack-default: 50;
    out property <int> envelope-decay-default: 300;
    out property <int> envelope-sustain-default: 200;
    out property <int> envelope-sustain-level-default: 6;
    out property <int> envelope-release-default: 300;

    // Auto Pan Sliders
    out property <float> auto-pan-course-speed-slider-step: 1;
    out property <float> auto-pan-course-speed-slider-minimum: 0;
    out property <float> auto-pan-course-speed-slider-maximum: 100;
    out property <float> auto-pan-course-speed-slider-default: 0;
    out property <float> auto-pan-fine-speed-slider-step: 0.01;
    out property <float> auto-pan-fine-speed-slider-minimum: 0.0;
    out property <float> auto-pan-fine-speed-slider-default: 0.01;
    out property <float> auto-pan-fine-speed-slider-maximum: 0.99;
    out property <float> auto-pan-width-slider-step: 0.1;
    out property <float> auto-pan-width-slider-minimum: 0.0;
    out property <float> auto-pan-width-slider-maximum: 2.0;
    out property <float> auto-pan-width-slider-default: 0.0;


    // Tremolo Sliders
    out property <float> tremolo-course-speed-slider-step: 1;
    out property <float> tremolo-course-speed-slider-minimum: 0;
    out property <float> tremolo-course-speed-slider-maximum: 100;
    out property <float> tremolo-course-speed-slider-default: 0;
    out property <float> tremolo-fine-speed-slider-step: 0.01;
    out property <float> tremolo-fine-speed-slider-minimum: 0.0;
    out property <float> tremolo-fine-speed-slider-default: 0.01;
    out property <float> tremolo-fine-speed-slider-maximum: 0.99;
    out property <float> tremolo-depth-slider-step: 0.01;
    out property <float> tremolo-depth-slider-minimum: 0.0;
    out property <float> tremolo-depth-slider-maximum: 1.0;
    out property <float> tremolo-depth-slider-default: 0.0;


    // Filter Mod Sliders
    out property <float> filter-mod-speed-slider-step: 0.01;
    out property <float> filter-mod-speed-slider-minimum: 0.01;
    out property <float> filter-mod-speed-slider-maximum: 20;
    out property <float> filter-mod-speed-slider-default: 1.0;
    out property <float> filter-mod-amount-slider-step: 0.01;
    out property <float> filter-mod-amount-slider-minimum: 0.0;
    out property <float> filter-mod-amount-slider-maximum: 1.0;
    out property <float> filter-mod-amount-slider-default: 0.0;

    // Phaser  Sliders
    out property <float> phaser-course-speed-slider-step: 1;
    out property <float> phaser-course-speed-slider-minimum: 0;
    out property <float> phaser-course-speed-slider-maximum: 100;
    out property <float> phaser-course-speed-slider-default: 0;
    out property <float> phaser-fine-speed-slider-step: 0.01;
    out property <float> phaser-fine-speed-slider-minimum: 0.0;
    out property <float> phaser-fine-speed-slider-default: 0.01;
    out property <float> phaser-fine-speed-slider-maximum: 0.99;
    out property <float> phaser-amount-slider-step: 1.0;
    out property <float> phaser-amount-slider-minimum: 0.0;
    out property <float> phaser-amount-slider-maximum: 128;
    out property <float> phaser-amount-slider-default: 40.0;

    // Bitshift  Sliders
    out property <int> bitcrush-amount-slider-step: 1;
    out property <int> bitcrush-amount-slider-minimum: 1;
    out property <int> bitcrush-amount-slider-maximum: 8;
    out property <int> bitcrush-amount-slider-default: 8;

    // Wave Shaper  Sliders
    out property <float> wave-shaper-amount-slider-step: 0.1;
    out property <float> wave-shaper-amount-slider-minimum: 0.0;
    out property <float> wave-shaper-amount-slider-maximum: 1.0;
    out property <float> wave-shaper-amount-slider-default: 0.0;

    // Gate Duty Cycle Slider
    out property <int> envelope-gate-duty-cycle-step: 1;
    out property <int> envelope-gate-duty-cycle-minimum: 5;
    out property <int> envelope-gate-duty-cycle-maximum: 90;
    out property <int> envelope-gate-duty-cycle-default: 50;
    out property <length> envelope-gate-duty-cycle-width: 100px;

    // Gate Note Length Slider
    out property <int> envelope-gate-note-length-step: 10;
    out property <int> envelope-gate-note-length-minimum: 10;
    out property <int> envelope-gate-note-length-maximum: 2000;
    out property <int> envelope-gate-note-length-default: 300;
    out property <length> envelope-gate-note-length-width: 100px;

    // Dynamics Compress Sliders
    out property <float> compressor-threshold-step: 1;
    out property <float> compressor-threshold-minimum: -30;
    out property <float> compressor-threshold-maximum: 0;
    out property <float> compressor-threshold-default: 0;
    out property <float> compressor-ratio-step: 1;
    out property <float> compressor-ratio-minimum: 1;
    out property <float> compressor-ratio-maximum: 10;
    out property <float> compressor-ratio-default: 2;

    // Wave Folder Sliders
    out property <float> wavefolder-threshold-step: 1;
    out property <float> wavefolder-threshold-minimum: -30;
    out property <float> wavefolder-threshold-maximum: 0;
    out property <float> wavefolder-threshold-default: 0;
    out property <float> wavefolder-ratio-step: 1;
    out property <float> wavefolder-ratio-minimum: 1;
    out property <float> wavefolder-ratio-maximum: 10;
    out property <float> wavefolder-ratio-default: 2;

    out property <float> limiter-threshold-step: 1;
    out property <float> limiter-threshold-minimum: -30;
    out property <float> limiter-threshold-maximum: 0;
    out property <float> limiter-threshold-default: 0;

    out property <float> clipper-threshold-step: 1;
    out property <float> clipper-threshold-minimum: -30;
    out property <float> clipper-threshold-maximum: 0;
    out property <float> clipper-threshold-default: 0;



    //
    // Label Text
    //
    out property <string> output-level-heading-text: "Output Level";
    out property <string> output-level-label-suffix: " dbfs";
    out property <string> oscillator1-heading-text: "Oscillator 1";
    out property <string> oscillator2-heading-text: "Oscillator 2";
    out property <string> oscillator3-heading-text: "Oscillator 3";
    out property <string> oscillator-tune-text: "Tuning";
    out property <string> oscillator-tune-value-text: "Unison";
    out property <string> oscillator-tune-value-suffix: " semitones";
    out property <string> sub-oscillator-heading-text: "Sub";
    out property <string> oscillator-level-text: "Level";
    out property <string> oscillator-shape-text: "Shape";
    out property <string> oscillator-mod-text: "Pitch Modulation";
    out property <string> oscillator-mod-speed-text: "Speed: ";
    out property <string> oscillator-mod-speed-suffix: " Hz";
    out property <string> oscillator-mod-amount-text: "Amount: ";
    out property <string> oscillator-mod-amount-suffix: "%";
    out property <string> detune-heading-text: "Detune";
    out property <string> detune-amount-label-suffix: "%";
    out property <string> envelope-header-text: "ADSR Envelope";
    out property <string> envelope-attack-text: "Attack";
    out property <string> envelope-decay-text: "Decay";
    out property <string> envelope-adsr-note-length-text: "Note Sustain Length";
    out property <string> envelope-sustain-level-text: "Sustain";
    out property <string> envelope-release-text: "Release";
    out property <string> envelope-time-suffix: " ms";
    out property <string> envelope-sustain-level-prefix: "Minus ";
    out property <string> envelope-sustain-level-suffix: " dbfs";
    out property <string> envelope-amp-mode-adsr-text: "ADSR";
    out property <string> envelope-amp-mode-gate-text: "Gate";
    out property <string> envelope-gate-note-length-text: "Gate Length";
    out property <string> envelope-gate-duty-cycle-text: "Duty Cycle";
    out property <string> envelope-mode-text: "Mode: ";
    out property <string> envelope-gate-duty-cycle-suffix: "%";
    out property <string> filter-header-text: "Low Pass Filter";
    out property <string> filter-cutoff-text: "Cutoff";
    out property <string> filter-resonance-text: "Resonance";
    out property <string> filter-cutoff-suffix: "%";
    out property <string> filter-poles-label-text: "Filter Poles: ";
    out property <string> auto-pan-heading-text: "Auto Pan";
    out property <string> auto-pan-speed-text: "Speed: ";
    out property <string> auto-pan-speed-suffix: " Hz";
    out property <string> auto-pan-width-text: "Width: ";
    out property <string> auto-pan-width-suffix: "%";
    out property <string> tremolo-speed-text: "Speed: ";
    out property <string> tremolo-speed-suffix: " Hz";
    out property <string> tremolo-depth-text: "Depth: ";
    out property <string> tremolo-depth-suffix: "%";
    out property <string> filter-mod-speed-text: "Speed: ";
    out property <string> filter-mod-speed-suffix: " Hz";
    out property <string> filter-mod-amount-text: "Amount: ";
    out property <string> filter-mod-amount-suffix: "%";
    out property <string> phaser-speed-text: "Speed: ";
    out property <string> phaser-speed-suffix: " Hz";
    out property <string> phaser-amount-text: "Shift: ";
    out property <string> phaser-heading-text: "Phaser";
    out property <string> bitcrush-amount-text: "Samples: ";
    out property <string> bitcrush-heading-text: "BitShift";
    out property <string> wave-shaper-speed-text: "Speed: ";
    out property <string> wave-shaper-amount-text: "Amount: ";
    out property <string> wave-shaper-heading-text: "Wave Shaper";
    out property <string> tremolo-heading-text: "Tremolo";
    out property <string> filter-modulation-heading-text: "Filter Mod";
    out property <string> compressor-heading-text: "Compressor";
    out property <string> compressor-threshold-text: "Threshold: ";
    out property <string> compressor-ratio-text: "Ratio: ";
    out property <string> compressor-ratio-suffix: ":1";
    out property <string> wavefolder-heading-text: "Wave Folder";
    out property <string> wavefolder-threshold-text: "Threshold: ";
    out property <string> wavefolder-ratio-text: "Ratio: ";
    out property <string> wavefolder-ratio-suffix: ":1";
    out property <string> limiter-heading-text: "Limiter";
    out property <string> limiter-threshold-text: "Threshold: ";
    out property <string> clipper-heading-text: "Clipper";
    out property <string> clipper-threshold-text: "Threshold: ";
    out property <string> slider-fine-text: "Fine: ";
    out property <string> slider-course-text: "Course: ";

}
