
export global Theme {

    // Main Window
    out property <string> window-title: "Oscillator Playground";
    out property <length> window-width: 1040px;
    out property <length> window-height: 550px;
    out property <length> window-border-width: 2px;
    out property <color> window-background: #101010;
    out property <color> border-colour: #333333;
    out property <length> border-width: 2px;
    out property <length> border-radius: 15px;
    out property <color> header-background: #252525;



    // Fonts
    out property <color> text-color: #aaaaaa;
    out property <color> greyed-out: #444444;
    out property <int> text-weight-bold: 800;
    out property <length> text-size: 12px;
    out property <length> label-text-size: 14px;
    out property <length> heading-text-size: 20px;


    //
    // Components
    //

    // Start Button
    out property <string> start-button-running-text: "Stop";
    out property <string> start-button-stopped-text: "Start";
    out property <length> start-button-width: 150px;
    out property <length> start-button-height: 35px;

    // Resync Button
    out property <string> resync-button-text: "Resync";
    out property <length> resync-button-width: 150px;
    out property <length> resync-button-height: 35px;

    // Detune Switch
    out property <length> mode-switch-width: 250px;
    out property <length> mode-switch-height: 30px;
    out property <length> mode-switch-spacer: 15px;

    // Output Level
    out property <int> output-level-minimum: -30;
    out property <int> output-level-maximum: 0;
    out property <int> output-level-step-size: 1;

    // Wave Selector
    out property <length> wave-shape-switch-width: 150px;
    out property <[string]> wave-shape-list: ["Sine", "Ramp", "Saw", "Square", "SuperSaw", "Triangle", "Noise"];
    out property <string> wave-shape-default: "Sine";

    // Oscillator Level Slider
    out property <int> osc-level-slider-step: 1;
    out property <int> osc-level-slider-minimum: 0;
    out property <int> osc-level-slider-maximum: 100;
    out property <int> osc-level-slider-default: 100;
    out property <int> sub-level-slider-default: 0;
    out property <int> detune-amount-slider-default: 0;


    // Filter Cutoff Slider
    out property <int> filter-cutoff-slider-step-factor: 0.05;
    out property <int> filter-cutoff-slider-minimum: 0;
    out property <int> filter-cutoff-slider-maximum: 18500;
    out property <int> filter-cutoff-slider-default: 18500;
    out property <int> filter-cutoff-display-adjustment-factor: 185;

    // Filter Resonance Slider
    out property <int> filter-resonance-slider-step: 1;
    out property <int> filter-resonance-slider-minimum: 40;
    out property <int> filter-resonance-slider-maximum: 100;
    out property <float> filter-resonance-slider-default: 100;

    // Filter Poles Slider
    out property <int> filter-poles-slider-step: 1;
    out property <int> filter-poles-slider-minimum: 1;
    out property <int> filter-poles-slider-maximum: 4;
    out property <int> filter-poles-slider-default: 2;
    out property <length> filter-poles-slider-width: 100px;

    // Output Level Slider
    out property <int> output-level-slider-step: 1;
    out property <int> output-level-slider-minimum: 40;
    out property <int> output-level-slider-maximum: 100;
    out property <int> output-level-slider-default: 90;

    // ADSR Slider 
    out property <int> milliseconds-slider-step: 10;
    out property <int> milliseconds-slider-minimum: 10;
    out property <int> milliseconds-slider-maximum: 1000;

    // Sustain Level Slider
    out property <int> envelope-sustain-level-step: 1;
    out property <int> envelope-sustain-level-minimum: 0;
    out property <int> envelope-sustain-level-maximum: 40;

    // Activation Switch
    out property <string> activation-switch-active-text: "Active";
    out property <string> activation-switch-not-active-text: "Not Active";
    out property <length> activation-switch-width: 150px;

    // Envelope ADRS Defaults
    out property <int> envelope-attack-default: 50;
    out property <int> envelope-decay-default: 300;
    out property <int> envelope-sustain-default: 200;
    out property <int> envelope-sustain-level-default: 6;
    out property <int> envelope-release-default: 300;

    // Envelope ADSR Box
    out property <color> adrs-box-background: #202020;


    // Gate Duty Cycle Slider
    out property <int> envelope-gate-duty-cycle-step: 1;
    out property <int> envelope-gate-duty-cycle-minimum: 5;
    out property <int> envelope-gate-duty-cycle-maximum: 90;
    out property <int> envelope-gate-duty-cycle-default: 50;
    out property <length> envelope-gate-duty-cycle-width: 100px;

    // Gate Note Length Slider
    out property <int> envelope-gate-note-length-step: 10;
    out property <int> envelope-gate-note-length-minimum: 10;
    out property <int> envelope-gate-note-length-maximum: 1000;
    out property <int> envelope-gate-note-length-default: 300;
    out property <length> envelope-gate-note-length-width: 100px;

    //
    // Label Text
    //

    out property <string> output-level-heading-text: "Output Level";
    out property <string> output-level-label-suffix: " dbfs";
    out property <string> oscillator1-heading-text: "Oscillator 1";
    out property <string> oscillator2-heading-text: "Oscillator 2";
    out property <string> oscillator3-heading-text: "Oscillator 3";
    out property <string> sub-oscillator-heading-text: "Sub";
    out property <string> sub-oscillator-level-text: "Relative Level";
    out property <string> oscillator-level-text: "Relative Level";
    out property <string> detune-heading-text: "Detune";
    out property <string> detune-amount-label-suffix: "%";
    out property <string> envelope-header-text: "ADSR Envelope";
    out property <string> envelope-attack-text: "Attack";
    out property <string> envelope-decay-text: "Decay";
    out property <string> envelope-sustain-text: "Sustain";
    out property <string> envelope-sustain-level-text: "Level";
    out property <string> envelope-release-text: "Release";
    out property <string> envelope-time-suffix: " ms";
    out property <string> envelope-sustain-level-prefix: "Output -";
    out property <string> envelope-sustain-level-suffix: "dbfs";
    out property <string> envelope-gate-text: "Gate";
    out property <string> envelope-amp-mode-gate-text: "ADSR";
    out property <string> envelope-amp-mode-envelope-text: "Gate";
    out property <string> envelope-gate-note-length-text: "Note Length";
    out property <string> envelope-gate-duty-cycle-text: "Duty Cycle";
    out property <string> envelope-mode-text: "Mode: ";
    out property <string> envelope-gate-duty-cycle-suffix: "%";
    out property <string> filter-header-text: "Low Pass Filter";
    out property <string> filter-cutoff-text: "Cutoff";
    out property <string> filter-resonance-text: "Resonance";
    out property <string> filter-cutoff-suffix: "%";
    out property <string> filter-poles-label-text: "Filter Poles: ";
}
